# Generated by Django 3.1.12 on 2022-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('categoty_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('categoty_type', models.CharField(max_length=20)),
                ('category_image', models.ImageField(upload_to='documents/categoryimage/')),
                ('slug', models.SlugField(default=models.CharField(max_length=20), unique=True)),
            ],
        ),
    ]
