# Generated by Django 3.1.12 on 2022-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_image', models.ImageField(upload_to='documents/tagimage/')),
                ('slug', models.SlugField(default=models.CharField(max_length=100), unique=True)),
            ],
        ),
    ]
