# Generated by Django 3.1.12 on 2022-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20220731_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
