# Generated by Django 4.0.6 on 2022-07-31 09:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20220731_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('blog_tilte', models.CharField(max_length=100)),
                ('blog_description', ckeditor.fields.RichTextField()),
                ('blog_tagLine', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('blog_category', models.ManyToManyField(blank=True, default='', to='blog_app.blogcategory')),
                ('blog_tag', models.ManyToManyField(blank=True, default='', to='blog_app.blogtags')),
            ],
        ),
    ]
