# Generated by Django 4.0.6 on 2022-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default=' ', upload_to='documents/blogimages/'),
            preserve_default=False,
        ),
    ]
