# Generated by Django 4.0.6 on 2022-08-02 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0010_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dislike',
            field=models.ManyToManyField(blank=True, default='', related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
